version: "3.8"

services:

  hadoop-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-namenode
    networks:
      - main-overlay-network
    ports:
      - 9870:9870
      - 9005:9000
    volumes:
      - type: bind
        source: ./hadoop-data/hadoop-namenode
        target: /hadoop/dfs/name
      - type: bind
        source: /home/vladislav/Yandex.Disk/UWCA
        target: /UWCA    
    environment:
        - CLUSTER_NAME=test
    env_file:
        - ./.env
    healthcheck:
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always

  hadoop-datanode-1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-datanode-1
    networks:
      - main-overlay-network
    volumes:
      - type: bind
        source: ./hadoop-data/hadoop-datanode-1
        target: /hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "hadoop-namenode:9870"
    env_file:
      - ./.env
    healthcheck:
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always


networks:
  main-overlay-network:
    external: true
    driver: overlay
    attachable: true