version: "3.8"

services:

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: zookeeper
    networks: 
      - main-overlay-network
    ports:
      - 2181:2181
    volumes:
      - type: bind
        source: zookeeper-data
        target: /bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    healthcheck:
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always

  kafka:
    image: docker.io/bitnami/kafka:3.1
    container_name: kafka
    networks: 
      - main-overlay-network
    ports:
      - 9092:9092
      - 9093:9093
    volumes:
      - type: bind
        source: kafka-data
        target: /bitnami 
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    healthcheck:
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always


networks:
  main-overlay-network:
    external: true
    driver: overlay
    attachable: true