version: "3.8"

services:

  postgres:
    image: postgres:13
    container_name: postgres
    networks: 
      - main-overlay-network
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    volumes:
      - type: bind
        source: ./data
        target: /var/lib/postgresql/data/
      - ./postgres.conf:/etc/postgresql/postgresql.conf
    ports:
      - 5432:5432
    env_file:
      - ./.env
    environment:
      PGDATA: /var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always

  
networks:
  main-overlay-network:
    external: true
    driver: overlay
    attachable: true
